name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 2.1.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  webview_flutter_android:
    #    path: ../flutter_plugins/packages/webview_flutter
    git:
      url: https://github.com/housmart/plugins.git
      path: packages/webview_flutter/webview_flutter_android
      ref: upgraded
  webview_flutter_platform_interface:
    #    path: ../flutter_plugins/packages/webview_flutter
    git:
      url: https://github.com/housmart/plugins.git
      path: packages/webview_flutter/webview_flutter_platform_interface
      ref: upgraded
  webview_flutter_wkwebview:
    #    path: ../flutter_plugins/packages/webview_flutter
    git:
      url: https://github.com/housmart/plugins.git
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: upgraded
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
